// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eljaixeawttlgxtjpuyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsamFpeGVhd3R0bGd4dGpwdXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzI1MzksImV4cCI6MjA3MzAwODUzOX0.jXDFIdpTwr8Ik8PO_YyA8Y3Y-IlHAl-C0oL-M2-prhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});